# Career-HY RAG 베이스라인 실험 설정
# 현재 서비스와 동일한 설정

experiment_name: "baseline"
description: "현재 서비스와 동일한 베이스라인 설정"
output_dir: "results"

# 임베딩 설정
embedder:
  type: "openai"
  model_name: "text-embedding-ada-002"
  batch_size: 5
  params: {}

# 청킹 설정 (현재 서비스는 청킹 사용 안함)
chunker:
  type: "no_chunk"
  chunk_size: null
  chunk_overlap: null
  params: {}

# 검색 시스템 설정
retriever:
  type: "chroma"
  collection_name: "job-postings-baseline"
  persist_directory: "/tmp/chroma_baseline"
  top_k: 10
  params: {}

# LLM 설정
llm:
  type: "openai"
  model_name: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 1000
  timeout: 30
  params: {}

# 데이터 설정
data:
  # s3_bucket은 환경변수 S3_BUCKET_NAME에서 설정
  pdf_prefix: "initial-dataset/pdf/"
  json_prefix: "initial-dataset/json/"
  ground_truth_path: "data/ground_truth.jsonl"
  test_queries_path: "data/test_queries.jsonl"

# 평가 설정
evaluation:
  metrics: ["recall@k", "precision@k", "mrr", "map", "ndcg@k"]
  k_values: [1, 3, 5, 10]
  use_langsmith: true
  langsmith_project: "Career-HY-Experiment"