# 청킹 전략 실험 설정

experiment_name: "chunking_recursive_1000"
description: "RecursiveCharacterTextSplitter로 청킹 (1000자, 200자 오버랩) 실험"
output_dir: "results"

# 임베딩 설정 (베이스라인과 동일)
embedder:
  type: "openai"
  model_name: "text-embedding-ada-002"
  batch_size: 5
  params: {}

# 청킹 설정 (실험 포인트)
chunker:
  type: "recursive"
  chunk_size: 1000
  chunk_overlap: 200
  params: {}

# 검색 시스템 설정
retriever:
  type: "chroma"
  collection_name: "job-postings-chunked"
  persist_directory: "/tmp/chroma_chunked"
  top_k: 10
  params: {}

# LLM 설정 (베이스라인과 동일)
llm:
  type: "openai"
  model_name: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 1000
  timeout: 30
  params: {}

# 데이터 설정
data:
  # s3_bucket은 환경변수 S3_BUCKET_NAME에서 설정
  pdf_prefix: "initial-dataset/pdf/"
  json_prefix: "initial-dataset/json/"
  ground_truth_path: "data/ground_truth.jsonl"
  test_queries_path: "data/test_queries.jsonl"

# 평가 설정
evaluation:
  metrics: ["recall@k", "precision@k", "mrr", "map", "ndcg@k"]
  k_values: [1, 3, 5, 10]
  use_langsmith: true
  langsmith_project: "Career-HY-Experiment"